### PR TITLE
Adding Subscription Flow

### PR DESCRIPTION
**Pull request by ShrutiChandak**
Adding subscription flow for new user to get access for EC portal

### CODE REVIEW

**Review by ayasuda-ge — CHANGES_REQUESTED** [review]
- Please remove "/public" react-built artifacts.
- Consolidate the folder "src" into the "web-assets". Remove "src" folder. Please refer to [this solution](https://stackoverflow.com/questions/44448851/how-do-i-change-src-folder-to-something-else-in-create-react-app)
- update react-script port in the package.json from "--port" to "PORT=xx". To use **.env** file, please refer to [this solution](https://stackoverflow.com/questions/40714583/how-to-specify-a-port-to-run-a-create-react-app-based-project)

@ShrutiChandak

**Comment by ayasuda-ge** [comment]
> * Please remove "/public" react-built artifacts.
> * Consolidate the folder "src" into the "web-assets". Remove "src" folder. Please refer to [this solution](https://stackoverflow.com/questions/44448851/how-do-i-change-src-folder-to-something-else-in-create-react-app)
> * update react-script port in the package.json from "--port" to "PORT=xx". To use **.env** file, please refer to [this solution](https://stackoverflow.com/questions/40714583/how-to-specify-a-port-to-run-a-create-react-app-based-project)
> 
> @ShrutiChandak

**Comment by ShrutiChandak** [comment]
> * Please remove "/public" react-built artifacts.
> * Consolidate the folder "src" into the "web-assets". Remove "src" folder. Please refer to [this solution](https://stackoverflow.com/questions/44448851/how-do-i-change-src-folder-to-something-else-in-create-react-app)
> * update react-script port in the package.json from "--port" to "PORT=xx". To use **.env** file, please refer to [this solution](https://stackoverflow.com/questions/40714583/how-to-specify-a-port-to-run-a-create-react-app-based-project)
> 
> @ShrutiChandak


> * Please remove "/public" react-built artifacts. - In progress(There are no artifacts and removed all unnecessary file)
> * Consolidate the folder "src" into the "web-assets". Remove "src" folder. Please refer to [this solution](https://stackoverflow.com/questions/44448851/how-do-i-change-src-folder-to-something-else-in-create-react-app) - Completed
> * update react-script port in the package.json from "--port" to "PORT=xx". To use **.env** file, please refer to [this solution](https://stackoverflow.com/questions/40714583/how-to-specify-a-port-to-run-a-create-react-app-based-project) - In progress
> 
> @ayasuda-ge

**Comment by ayasuda-ge** [comment]
> > * Please remove "/public" react-built artifacts.
> > * Consolidate the folder "src" into the "web-assets". Remove "src" folder. Please refer to [this solution](https://stackoverflow.com/questions/44448851/how-do-i-change-src-folder-to-something-else-in-create-react-app)
> > * update react-script port in the package.json from "--port" to "PORT=xx". To use **.env** file, please refer to [this solution](https://stackoverflow.com/questions/40714583/how-to-specify-a-port-to-run-a-create-react-app-based-project)
> > 
> > @ShrutiChandak
> 
> > * Please remove "/public" react-built artifacts. - Completed(There are no artifacts and removed all unnecessary file)
> > * Consolidate the folder "src" into the "web-assets". Remove "src" folder. Please refer to [this solution](https://stackoverflow.com/questions/44448851/how-do-i-change-src-folder-to-something-else-in-create-react-app) - Completed
> > * update react-script port in the package.json from "--port" to "PORT=xx". To use **.env** file, please refer to [this solution](https://stackoverflow.com/questions/40714583/how-to-specify-a-port-to-run-a-create-react-app-based-project) - Completed
> > 
> > @ayasuda-ge

- **/public** is not removed.
- where is the **.env**?
- where are the ```index.html``` and ```logout.html``` under ```/webui-assets```?

Further discussion-

- how seeder loads the ```.env```
- how to utilise the ```/build``` artifacts folder generate by react.
- how to persist the ui runtime variables.

**Comment by ShrutiChandak** [comment]
> > > * Please remove "/public" react-built artifacts.
> > > * Consolidate the folder "src" into the "web-assets". Remove "src" folder. Please refer to [this solution](https://stackoverflow.com/questions/44448851/how-do-i-change-src-folder-to-something-else-in-create-react-app)
> > > * update react-script port in the package.json from "--port" to "PORT=xx". To use **.env** file, please refer to [this solution](https://stackoverflow.com/questions/40714583/how-to-specify-a-port-to-run-a-create-react-app-based-project)
> > > 
> > > @ShrutiChandak
> > 
> > 
> > > * Please remove "/public" react-built artifacts. - Completed(There are no artifacts and removed all unnecessary file)
> > > * Consolidate the folder "src" into the "web-assets". Remove "src" folder. Please refer to [this solution](https://stackoverflow.com/questions/44448851/how-do-i-change-src-folder-to-something-else-in-create-react-app) - Completed
> > > * update react-script port in the package.json from "--port" to "PORT=xx". To use **.env** file, please refer to [this solution](https://stackoverflow.com/questions/40714583/how-to-specify-a-port-to-run-a-create-react-app-based-project) - Completed
> > > 
> > > @ayasuda-ge
> 
> * **/public** is not removed.
> * where is the **.env**?
> * where are the `index.html` and `logout.html` under `/webui-assets`?
> 
> Further discussion-
> 
> * how seeder loads the `.env`
> * how to utilise the `/build` artifacts folder generate by react.
> * how to persist the ui runtime variables.

> * **/public** is not removed. - Made the configuration changes and removed public folder.
> * where is the **.env**? - Added along with PORT name property
> * where are the `index.html` and `logout.html` under `/webui-assets`? - Added again from the existing code and configured  it so that code won't take index.html from public folder.

**Comment by ayasuda-ge** [comment]
> > > > * Please remove "/public" react-built artifacts.
> > > > * Consolidate the folder "src" into the "web-assets". Remove "src" folder. Please refer to [this solution](https://stackoverflow.com/questions/44448851/how-do-i-change-src-folder-to-something-else-in-create-react-app)
> > > > * update react-script port in the package.json from "--port" to "PORT=xx". To use **.env** file, please refer to [this solution](https://stackoverflow.com/questions/40714583/how-to-specify-a-port-to-run-a-create-react-app-based-project)
> > > > 
> > > > @ShrutiChandak
> > > 
> > > 
> > > > * Please remove "/public" react-built artifacts. - Completed(There are no artifacts and removed all unnecessary file)
> > > > * Consolidate the folder "src" into the "web-assets". Remove "src" folder. Please refer to [this solution](https://stackoverflow.com/questions/44448851/how-do-i-change-src-folder-to-something-else-in-create-react-app) - Completed
> > > > * update react-script port in the package.json from "--port" to "PORT=xx". To use **.env** file, please refer to [this solution](https://stackoverflow.com/questions/40714583/how-to-specify-a-port-to-run-a-create-react-app-based-project) - Completed
> > > > 
> > > > @ayasuda-ge
> > 
> > 
> > 
> > * **/public** is not removed.
> > * where is the **.env**?
> > * where are the `index.html` and `logout.html` under `/webui-assets`?
> > 
> > Further discussion-
> > 
> > * how seeder loads the `.env`
> > * how to utilise the `/build` artifacts folder generate by react.
> > * how to persist the ui runtime variables.
> 
> > * **/public** is not removed. - Made the configuration changes and removed public folder.
> > * where is the **.env**? - Added along with PORT name property
> > * where are the `index.html` and `logout.html` under `/webui-assets`? - Added again from the existing code and configured  it so that code won't take index.html from public folder.

Okay.. index.html is now the entry. There are the problems as follows-
1. where is the ```App.js``` being loaded? there appears a missing loader.
2. Those external links [line 1208](https://github.com/ShrutiChandak/web-ui/blob/v1.1beta/webui-assets/index.html#L1208), [line 1232](https://github.com/ShrutiChandak/web-ui/blob/v1.1beta/webui-assets/index.html#L1232) should not be loaded.

**Comment by ShrutiChandak** [comment]
> > > > > * Please remove "/public" react-built artifacts.
> > > > > * Consolidate the folder "src" into the "web-assets". Remove "src" folder. Please refer to [this solution](https://stackoverflow.com/questions/44448851/how-do-i-change-src-folder-to-something-else-in-create-react-app)
> > > > > * update react-script port in the package.json from "--port" to "PORT=xx". To use **.env** file, please refer to [this solution](https://stackoverflow.com/questions/40714583/how-to-specify-a-port-to-run-a-create-react-app-based-project)
> > > > > 
> > > > > @ShrutiChandak
> > > > 
> > > > 
> > > > > * Please remove "/public" react-built artifacts. - Completed(There are no artifacts and removed all unnecessary file)
> > > > > * Consolidate the folder "src" into the "web-assets". Remove "src" folder. Please refer to [this solution](https://stackoverflow.com/questions/44448851/how-do-i-change-src-folder-to-something-else-in-create-react-app) - Completed
> > > > > * update react-script port in the package.json from "--port" to "PORT=xx". To use **.env** file, please refer to [this solution](https://stackoverflow.com/questions/40714583/how-to-specify-a-port-to-run-a-create-react-app-based-project) - Completed
> > > > > 
> > > > > @ayasuda-ge
> > > 
> > > 
> > > 
> > > * **/public** is not removed.
> > > * where is the **.env**?
> > > * where are the `index.html` and `logout.html` under `/webui-assets`?
> > > 
> > > Further discussion-
> > > 
> > > * how seeder loads the `.env`
> > > * how to utilise the `/build` artifacts folder generate by react.
> > > * how to persist the ui runtime variables.
> > 
> > 
> > > * **/public** is not removed. - Made the configuration changes and removed public folder.
> > > * where is the **.env**? - Added along with PORT name property
> > > * where are the `index.html` and `logout.html` under `/webui-assets`? - Added again from the existing code and configured  it so that code won't take index.html from public folder.
> 
> Okay.. index.html is now the entry. There are the problems as follows-
> 
> 1. where is the `App.js` being loaded? there appears a missing loader.
> 2. Those external links [line 1208](https://github.com/ShrutiChandak/web-ui/blob/v1.1beta/webui-assets/index.html#L1208), [line 1232](https://github.com/ShrutiChandak/web-ui/blob/v1.1beta/webui-assets/index.html#L1232) should not be loaded. - 

> 
> 1. where is the `App.js` being loaded? there appears a missing loader. - [Please refer this](https://stackoverflow.com/questions/41738421/how-react-js-index-js-file-contacting-index-html-for-id-references)
> 2. Those external links [line 1208](https://github.com/ShrutiChandak/web-ui/blob/v1.1beta/webui-assets/index.html#L1208), [line 1232](https://github.com/ShrutiChandak/web-ui/blob/v1.1beta/webui-assets/index.html#L1232) should not be loaded. - Removed those from Index.html

**Comment by ayasuda-ge** [comment]
@ShrutiChandak  @ramaraosrikakulapu @Puja129 

The PR proposal is not mergeable with its commits due to a secret exposure in history. Boostrapped a clean branch instead for the continue UI development. #close

**Pull request closed without merging**
