### PR TITLE
For Issue -Remote Management UI (Portal 1.x)]

### LINKED ISSUE #111: Remote Management UI (Portal 1.x)
As an Ops agent, I want to run the EC 
Portal 1.x in k8s env, and able to remotely control agents that were deployed in the k8s.

**Subhash**

### PR DESCRIPTION
**Pull request by Subhash-vishwakarma**
Starting a PR for the issue -
[Remote Management UI (Portal 1.x)](https://github.com/orgs/EC-Release/projects/3#card-56303033) #111

### CODE REVIEW

**Comment by Subhash-vishwakarma** [comment]
@ayasuda2OO3 added the remote UI components and files to operate locally in a separate folder  **remote web-ui**

**Comment by Subhash-vishwakarma** [comment]
@ayasuda-ge  I have added the Gateway Details tab and details under the page.
Adding the Screenshot of that.
image

**Comment by vidya22022** [comment]
@ayasuda-ge  
working on maintaincreate and group create unit testing

**Comment by Subhash-vishwakarma** [comment]
@ayasuda-ge  for the issue facing in loading the UI in portal. Below api is not giving any response 
"/v1.1beta/ec/getDevId" which is used in app.js. I need a dummy response for this api to mock the data in UI.

**Comment by Subhash-vishwakarma** [comment]
@ayasuda-ge  I have created two templates  for Gateway details page. Let me know which one would you think would be better to keep


 image

 image

**Comment by Subhash-vishwakarma** [comment]
@ayasuda-ge I have added the gateway operation buttons to the healthStatus Tab. Attaching the SS for reference.

 
image

**Comment by ayasuda-ge** [comment]
> @ayasuda-ge
> working on maintaincreate and group create unit testing

Please open a PR @vidya22022 for the progress

**Pull request closed without merging**
